### PR TITLE
Regenerate package-lock.json

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by nikolas** [comment]
@ndittren the regenerated package-lock caused some eslint failures which I resolved, but I wanted you to take a look at this because it's typescript stuff I'm not that familiar with so I want to make sure I'm fixing things in the right way here.

**Comment by nikolas** [comment]
Oh, it looks like my eslint fixes actually caused issues in the tests. I can take a look here as well, but this is lower priority. I just wanted to update things here bc there were a few faculty requests this week.

**Comment by ndittren** [comment]
> lower

Yea

**Comment by ndittren** [comment]
Whoops. Wrong click. Yeah so for the functions you either have a 

`cancelFunc(): void;` for class functions or `cancelFunc: () => void` for others. And if it takes any arguments, that has to be typed as well like this `startPatientPanel(panel: number): void;`

**Comment by nikolas** [comment]
Closing in favor of: https://github.com/ccnmtl/austere-med-interactives/pull/926

**Pull request closed without merging**
